### PR TITLE
Multiple quality improvements

### PR DESCRIPTION
**Pull request by m-ezzat**
This pull request is focused on resolving occurrences of Sonar rules squid:HiddenFieldCheck - Local variables should not shadow class fields
squid:S1192 - String literals should not be duplicated

You can find more information about the issues here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:HiddenFieldCheck
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1192

Please let me know if you have any questions.

M-Ezzat

### CODE REVIEW

**Comment by cslinmiso** [comment]
This PR seems problematic, for instance, the charset format set to UTF-8 and it cannot be UTF_8.

**Comment by m-ezzat** [comment]
Hi @cslinmiso I don't think that this is a problem, cause it's clear for the developers that this is the naming convention, and it the underscore can be used instead of any space or character.

**Comment by m-ezzat** [comment]
You can find this example in Java APIs <code>java.nio.charset.StandardCharsets.UTF_8</code>

**Comment by cslinmiso** [comment]
Thanks, I misread some of your code.

**Pull request merged**
